### ISSUE TITLE
Immigration

### ISSUE THREAD

**Issue by jescoyle** [hurlbertlab/core-transient-simulation#5]
The migrate() function stochastically adds a species to an empty place with probability _m_ and then draws that species from a given global species abundance distribution.
1. What range of immigration rates _m_ should be examined?
2. Should all species have equal probability or if not, what distribution should be used? (See make_sad() function)

**Comment by ahhurlbert** [comment]
Can you clarify when migrate() is supposed to happen in the workflow. Currently, it is never called as far as I can tell.

And this is a replacement from the metacommunity species pool, as opposed to dispersal() which is within landscape "migration", yes?

Are there every "empty place"s? What do you mean by that. In neutral theory, the migration parameter controls the filling of a space left by a dying individual because it's an IBM, but it's unclear what the analog should be here.

Is it that once a species goes extinct from the landscape, a new species is drawn to replenish?

**Comment by jescoyle** [comment]
migrate() is called from the function establish() (lines 503-534 in simulations_functions.R), which takes a pool of propagules for a given cell and first tries to fill empty spaces with migrants from outside the landscape, then tries to fill the spaces with a random draw of the propagules. Hence, _m_ is the probability that an empty space is filled by a colonist from the global SAD. 

Empty spaces occur when an individual dies or when a propagule fails to establish and the space is carried over to the next time step (when recruitment rates < 1). Empty spaces also occur in the beginning of the simulation if the landscape doesn't start at its carrying capacity.

establish() controls how empty spaces are filled. disperse() controls how propagules move.

**Comment by ahhurlbert** [comment]
Ok, seems like m should be quite low. 0.01 or lower? This is a parameter that I don't think needs to be explored too much once basic simulation dynamics are established.

I would suggest assigning colonists from a global lognormal SAD (in which preferred habitat is randomly assigned, so there are common and rare species of each).

**Comment by jescoyle** [comment]
Agreed.

Should the global SAD be proportional to species birth rates (which is how differences in abundance are generated), or independent?
